### ISSUE TITLE
Allow customizing check frequency

### ISSUE THREAD

**Issue by jlebon** [coreos/zincati#203]
Writing an update test, and I'd like Zincati to be able to check for updates much faster for the purpose of the test. I see there's a related TODO to this:

https://github.com/coreos/zincati/blob/eb55d9364ab5afbc441488c8fede9f2a9279c898/src/update_agent/mod.rs#L157-L160

Config knob works, or if we're not ready to commit to an interface yet, an env var also would be OK.

**Comment by lucab** [comment]
Yes, I agree it is a good thing to fix that TODO and make this configurable.
The first step in that direction is to split this field, so that each state has its own pause duration.

Once there, what should the configuration looks like? It sounds like you need an aggressive refresh loop while the agent is in the steady state. A non-zero number of seconds may suit?

How does the below strawman sound?
```toml

# Configure update-agent pace.
[agent.timing]
# Pausing interval between updates checks in steady mode, in seconds.
steady_interval_secs = N

## Further settings, maybe later.
# Pausing interval between finalization attempts, in seconds.
# finalization_interval_secs = N
```
