### ISSUE TITLE
strategy: add weekly maintenance windows mode, configuration and logic

### ISSUE THREAD

**Issue by lucab** [coreos/zincati#34]
Zincati needs to have an additional update strategy, called "periodic". This is used to schedule update finalization (i.e. host reboot) locally on each node, based on current datetime and configuration.

This is used to configure what's normally called a "maintenance window" for OS reboot. Prior art for this is https://github.com/coreos/locksmith#reboot-windows.

A `StrategyPeriodic` will be in charge of gating the "finalize-deployment" call, only allowing it when local time is within the configured window.

Configuration options to add:
 * a `updates.strategy = periodic` variant
 * a `strategy.periodic` section
 * a list of finalization `[[window]]`, each one containing:
    - a list of short-day-names (like `date %a` in C local, i.e. `[ "Mon", "Wed" ]`)
    - a window start time, in 24h format (i.e. `23:45`)
    - window length, in minutes
    - ~~UTC (bool, default: `true`). Still unsure about this, see https://github.com/coreos/airlock/issues/13#issuecomment-501349851.~~

Note: this relies on local node clock and time configuration. Fedora CoreOS docs should recommend running an NTP client, and setting host timezone to UTC.

**Comment by Limero** [comment]
This is the missing piece for me migrating my home server to Fedora CoreOS. I can't have it randomly restart while I use it, so scheduling updates during the night would be perfect.

**Comment by lucab** [comment]
Made some progress on this, I've currently wired up the following configuration in #47:

```toml
[updates]
strategy = "weekly"

[[updates.weekly.window]]
days = [ "Sat", "Sun" ]
start_time = "23:30"
length_minutes = 60

[[updates.weekly.window]]
days = [ "Wed" ]
start_time = "01:00"
length_minutes = 30
```

Punting on the "local timezone" setting for the moment, as Daylight Saving Time (DST) switches and timezone-law changes have many nasty side-effects on maintenance windows.
